"""renamed column in complaint model

Revision ID: 06d09a949c6a
Revises: 66c365b27279
Create Date: 2022-11-06 19:04:00.213792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d09a949c6a'
down_revision = '66c365b27279'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('complainer_id', sa.Integer(), nullable=False))
    op.drop_constraint('complaints_Complainer_id_fkey', 'complaints', type_='foreignkey')
    op.create_foreign_key(None, 'complaints', 'users', ['complainer_id'], ['id'])
    op.drop_column('complaints', 'Complainer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('Complainer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.create_foreign_key('complaints_Complainer_id_fkey', 'complaints', 'users', ['Complainer_id'], ['id'])
    op.drop_column('complaints', 'complainer_id')
    # ### end Alembic commands ###
