"""renamed column in complaint model- tittle to title

Revision ID: 6faf32e02839
Revises: 06d09a949c6a
Create Date: 2022-11-06 19:24:56.300467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6faf32e02839'
down_revision = '06d09a949c6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('title', sa.String(length=120), nullable=False))
    op.drop_column('complaints', 'tittle')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('tittle', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('complaints', 'title')
    # ### end Alembic commands ###
